export const mockBoards = [
  {
    id: "1",
    title: "Marketing Creativo",
    description: "Plan de campañas para nuevos productos",
    coverImage: "/assets/images/img1.jpg",
    updatedAt: "2025-07-24T10:00:00Z",
    isFavorite: true,
    members: [
      { id: "u1", name: "Lucía", avatar: "/assets/icons/avatar1.png" },
      { id: "u2", name: "Pedro", avatar: "/assets/icons/avatar2.png" },
    ],
    tags: ["Publicidad", "Diseño"],
  },
  {
    id: "2",
    title: "Sprint Frontend",
    description: "Implementación de vistas responsivas",
    coverImage: "/assets/images/img2.jpg",
    updatedAt: "2025-07-23T14:30:00Z",
    isFavorite: false,
    members: [
      { id: "u3", name: "Ana", avatar: "/assets/icons/avatar3.png" },
      { id: "u4", name: "Luis", avatar: "/assets/icons/avatar2.png" },
    ],
    tags: ["React", "Tailwind"],
  },
  {
    id: "3",
    title: "Tablero Vacío",
    description: "",
    coverImage: "/assets/images/img3.jpg",
    updatedAt: "2025-07-20T08:15:00Z",
    isFavorite: false,
    members: [],
    tags: [],
  },
  {
    id: "4",
    title: "Diseño UI/UX",
    description: "Mockups y prototipos para el rediseño de app",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-22T11:45:00Z",
    isFavorite: false,
    members: [
      { id: "u5", name: "Carlos", avatar: "/assets/icons/avatar1.png" },
    ],
    tags: ["Figma"],
  },
  {
    id: "5",
    title: "Clientes",
    description: "Seguimiento de cuentas clave",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-22T13:30:00Z",
    isFavorite: false,
    members: [],
    tags: ["CRM"],
  },
  {
    id: "6",
    title: "Eventos 2025",
    description: "Agenda y organización de eventos empresariales",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-21T09:00:00Z",
    isFavorite: false,
    members: [
      { id: "u6", name: "Verónica", avatar: "/assets/icons/avatar2.png" },
    ],
    tags: ["Logística"],
  },
  {
    id: "7",
    title: "Soporte Técnico",
    description: "Gestión de incidencias y bugs",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-21T15:00:00Z",
    isFavorite: false,
    members: [],
    tags: ["QA"],
  },
  {
    id: "8",
    title: "Contabilidad",
    description: "Flujo de caja y balances mensuales",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-20T18:00:00Z",
    isFavorite: false,
    members: [
      { id: "u7", name: "Laura", avatar: "/assets/icons/avatar3.png" },
    ],
    tags: ["Finanzas"],
  },
  {
    id: "9",
    title: "Investigación",
    description: "Exploración de nuevas tecnologías",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-19T12:00:00Z",
    isFavorite: false,
    members: [],
    tags: ["Innovación"],
  },
  {
    id: "10",
    title: "Capacitación",
    description: "Programas internos de formación",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-18T14:15:00Z",
    isFavorite: false,
    members: [
      { id: "u8", name: "Martín", avatar: "/assets/icons/avatar2.png" },
    ],
    tags: ["RH", "Cursos"],
  },
  {
    id: "11",
    title: "Estrategia Q3",
    description: "Análisis y objetivos del trimestre",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-17T10:45:00Z",
    isFavorite: false,
    members: [],
    tags: ["Planeación"],
  },
];